### PR TITLE
Create codechef_soln.cpp

### PR DESCRIPTION
**Pull request by nishant6897**

### CODE REVIEW

**Review by malivinayak — CHANGES_REQUESTED** [review]
Rename the program appropriately
Kindly go through contribution Rules and follow them strictly also follow the file structure
Make appropriate changes and I will accept your PR

**Comment by malivinayak** [comment]
@nishant6897 

## Rules
* Do not <b>spam!</b>
* Do not copy paste codes write your own code.<br>
* Refer Hello_Multi_Programming to understand the structure.
* Maintain the structure as follows
>  Program_Category [This is a main folder]
>  
>   > 1. Program_Category_Name
>   >  
>   >  >  1. Program_Name
>   >  > 
>   >  >> **src** : Contains Program same as folder name in different languages <br> 
>   >  >> **README.md** : Problem Statement, Solution in different Programming Language with its hyperlink
>   >  > 2. README.md
>   >  > 
>   >  >> Program Name List of respective category
>   >  >  
>   >  2. README.md 
>   >
>   >  > Category List
> 
  <hr>

[Click Here to see Rules](https://github.com/malivinayak/Multi-Programming/blob/main/CONTRIBUTING.md#rules)

**Comment by malivinayak** [comment]
You just changed the file name
The folder in which you uploaded the code is just for hello_multi_programming Code

Delete that file 
Upload Simple addition program in any language [Here](https://github.com/malivinayak/Multi-Programming/tree/main/Program_Category/01_Fundamentals/Addition)
Link For Folder - [Click Here](https://github.com/malivinayak/Multi-Programming/tree/main/Program_Category/01_Fundamentals/Addition)

Upload addition program under src folder only

**Comment by malivinayak** [comment]
First you have to sync the changes to make your repo upto date

**Comment by nishant6897** [comment]
please merge now .

**Comment by malivinayak** [comment]
@nishant6897 Already merged with label [hacktoberfest-accepted](https://github.com/malivinayak/Multi-Programming/labels/hacktoberfest-accepted)

**Pull request merged**
