### PR TITLE
created CODE FOR MERGE Sort and updated All readme files 

### PR DESCRIPTION
**Pull request by akhilmishra365**
Sir tried another pull request in this repo after trying many times finally able to successfully create a pull request please provide your review

### CODE REVIEW

**Comment by malivinayak** [comment]
Looks Good

**Comment by akhilmishra365** [comment]
Please merge it to the main
😇

**Comment by malivinayak** [comment]
Alrwady merge @akhilmishra365

**Comment by akhilmishra365** [comment]
SIR
CAN I MERGE  MORE CODES IN YOUR REPO ?

**Comment by malivinayak** [comment]
Yes you can

**Comment by malivinayak** [comment]
If you want then create 3 more PR's here only

**Comment by malivinayak** [comment]
Also, your contribution is welcome at [malivinayak/markdown](https://github.com/malivinayak/Markdown)

**Pull request merged**
